name: Build-and-test
on: [push]

permissions:
  pull-requests: read # allows SonarCloud to decorate PRs with analysis results
  security-events: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Test
      run: >
        cd SteamPrefill.Test;
        dotnet test --no-restore -c Release
  infersharp:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: dotnet build -c Debug
    - name: Run Infer#      
      uses: microsoft/infersharpaction@v1.3.1
      id: runinfersharp
      with:
        binary-path: SteamPrefill/bin/Debug/net6.0
        optional-flags: --enable-null-dereference --enable-dotnet-resource-leak --enable-thread-safety-violation
    - name: Upload SARIF output to GitHub Security Center
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: infer-out/report.sarif
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runtime: ['win-x64', 'linux-x64', 'linux-arm64', 'osx-x64']
      fail-fast: false
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Publish
      # WarningLevel=0 so that the Annotations don't hide the Artifact list
      run: >
        dotnet publish SteamPrefill/SteamPrefill.csproj \
          --nologo \
          -o publish \
          -c Release \
          --runtime "${{ matrix.runtime }}" \
          --self-contained true \
          /p:WarningLevel=0 \
          /p:PublishSingleFile=true 
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        # TODO the uploaded file name needs to be improved to include branch name + date
        name: "${{ matrix.runtime }}"
        path: publish/